const general = [
    { question: "What was your favourite movie when you were younger?" },
    { question: "What is your favourite meal?" },
    { question: "What are your favourite snacks to eat?" },
    {question: "What time do you go to sleep and wake up?"},
    {question: "Please talk about your favourite memory."},
    {question: "If you one a billion yen, what things would you buy and do?"},
    {question: "Please tell the class something interesting you have heard lately."},
    {question: "What's been the best thing that's happened to you this year?"},
    {question: "What do you and your friends like to do?"},
    {question: "How would you like to spend your weekend?"},
    {question: "What's your favourite restaurant?"},
    {question: "Please tell the class an interesting fact about yourself?"},
    {question: "What famous person would you like to meeet and why?"},
    {question: "If you could have a pet, what would it be?"},
    {question: "Where was the last place you went to with your parents?"},
    {question: "Do your grandparents live in Tokyo?"},
    {question: "Your favourite place in Tokyo?"},
    {question: "How often do you eat snacks?"},
    {question: "Last time you laughed?"},
    {question: "What do you and your friends like to do together?"},
    {question: "Have you ever witnessed a crime?"},
    {question: "Last time you cried?"},
    {question: "What's your favourite season, why?"},
    {question: "Have you ever broken a bone?"},
    {question: "Something you would like to buy?"},
  ];
  
  export default general;