const random = [
    { question: "How often do you exercise a week?" },
    {question: "Do you enjoy to exercise?"},
    {question: "Is there an unhealthy habit you should stop?"},
    {question: "What's the most embarrassing thing that's happened to you?"},
    {question: "What's your favourite movie?"},
    {question: "What things make you happy?"},
    {question: "How often do you get your haircut?"},
    {question: "What do you dislike about your school?"},
    {question: "What are you most looking forward too in the future?"},
    {question: "What's the best thing about your school?"},
    {question: "Favourite animal and why?"},
    {question: "A surprising fact about you?"},
    {question: "What's your biggest wish?"},
    {question: "The most difficult thing you've done?"},
    {question: "Something that scares you?"},
    {question: "What's your favourite drink and why?"},
    {question: "What would be your dream future job?"},
    {question: "Have you ever done something you regret?"},
    {question: "Something you are good at?"},
    {question: "Favourite ice cream?"},
    {question: "Something you dislike?"},
    {question: "If you moved, where would you like to live?"},
    {question: "If you could have a superpower, what would it be?"},
    {question: "Would you like the power to travel through time?"},
    {question: "If you were granted 3 wishes what would they be?"},
    {question: "favourite fast food restaurant?"},

  ];
  
  export default random;