const travel = [
    {question: "Where would you most like to visit in Europe and why?" },
    {question: "Describe the last trip you had." },
    {question: "What was your favourite holiday ever?" },
    {question: "Where would you most like to visit in North America?"},
    {question: "Describe your ideal holiday?"},
    {question: "Would you like to work/study abroad, Why/why not?"},
    {question: "If you were given a free ticket to anywhere in the world, where would you go?"},
    {question: "Where would you most like to visit in Japan?"},
    {question: "Apart from Japan, which Asian country would you most like to visit, why?"},
    {question: "Which famous historical place would you most like to visit?"},
    {question: "In detail, please recommend a place for people to visit, and why they should visit."},
    {question: "Do you have any travel plans this year?"},
    {question: "Have you had a holiday somewhere this year?"},
    {question: "Which countries food do you think is the best?"},
    {question: "Please name three countries you would like to visit and why."},
    {question: "What do you miss most about your own country when you travel abroad?"},
    {question: "Name two cities you would most like to visit?"},
    {question: "What foreign country's culture most interests you, why?"},
    {question: "Do you like traveling by Aeroplane, please explain."},
    {question: "Have you ever used English when travelling abroad? Please explain."},
    {question: "Where would you like to visit in Asia?"},
    {question: "If you had to leave Japan, where would you live and why?"},
    {question: "A country you'd never like to visit, why?"},
    {question: "Favourite place in Tokyo?"},
    {question: "Best place you've ever been?"},
    {question: "Apart from English, what language would you like to learn?"},
    {question: "Would you like to climb Mount Everest?"},
    {question: "Would you like to see the Great Pyramid in Egypt?"},
    {question: "Could you name the seven wonders of the world?"},
    {question: "Would you like to visit Australia?"},
    {question: "Do you know what country your teacher is from?"},
    {question: "Which country would you like to visit with your best friend?"},
  ];
  
  export default travel;